language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"

before_script:
  - composer self-update
  - composer update

script:
  - phpunit --configuration phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
